#!/usr/bin/env bash
# Installs the `delegate` launcher into ~/.claude/bin and seeds config.
# Works on Linux, macOS, and Windows Git Bash. Run: bash install.sh
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLAUDE_DIR="$HOME/.claude"
BIN_DIR="$CLAUDE_DIR/bin"
CMD_DIR="$CLAUDE_DIR/commands"
LAUNCHER="$BIN_DIR/delegate"
CONFIG="$CLAUDE_DIR/delegate.config.json"

# Pick a Python 3 interpreter.
PY=""
for c in python3 python py; do
  if command -v "$c" >/dev/null 2>&1; then
    if "$c" -c 'import sys; sys.exit(0 if sys.version_info[0]==3 else 1)' 2>/dev/null; then
      PY="$c"; break
    fi
  fi
done
[ -z "$PY" ] && { echo "install: no Python 3 found on PATH. Install Python 3.8+ first." >&2; exit 1; }

mkdir -p "$BIN_DIR"

cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# Auto-generated by the Delegation Pipeline installer. Points at the repo checkout.
exec "$PY" "$REPO_DIR/delegate.py" "\$@"
EOF
chmod +x "$LAUNCHER"
echo "installed launcher -> $LAUNCHER"

if [ ! -f "$CONFIG" ]; then
  cp "$REPO_DIR/config.example.json" "$CONFIG"
  echo "seeded config   -> $CONFIG"
else
  echo "config exists   -> $CONFIG (left unchanged)"
fi

# Slash commands and skills ship with the plugin, not this installer, so they are not
# copied here (that would duplicate the plugin's commands). Install the plugin for
# /delegate + /orchestrate and the delegate/orchestrate skills:
echo
echo "For the /delegate + /orchestrate commands and skills, install the plugin:"
echo "  claude plugin marketplace add aayushpokhrel1/delegation-pipeline"
echo "  claude plugin install delegation-pipeline"

echo
echo "Done. Test it:"
echo "  ~/.claude/bin/delegate free \"list the files here and summarize the project\""
echo
echo "For deepseek/kimi/nvidia/openrouter, set your keys (env vars or edit $CONFIG):"
echo "  export DEEPSEEK_API_KEY=sk-..."
echo "  export MOONSHOT_API_KEY=sk-..."
echo "  export NVIDIA_API_KEY=nvapi-..."
echo "  export OPENROUTER_API_KEY=sk-or-...   # https://openrouter.ai/keys"
echo "For the free backend, run OmniRoute in another terminal:  npx omniroute"
