#!/usr/bin/env bash
# Installs the `delegate` launcher into ~/.claude/bin and seeds config.
# Works on Linux, macOS, and Windows Git Bash. Run: bash install.sh
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLAUDE_DIR="$HOME/.claude"
BIN_DIR="$CLAUDE_DIR/bin"
CMD_DIR="$CLAUDE_DIR/commands"
LAUNCHER="$BIN_DIR/delegate"
CONFIG="$CLAUDE_DIR/delegate.config.json"

# Pick a Python 3 interpreter.
PY=""
for c in python3 python py; do
  if command -v "$c" >/dev/null 2>&1; then
    if "$c" -c 'import sys; sys.exit(0 if sys.version_info[0]==3 else 1)' 2>/dev/null; then
      PY="$c"; break
    fi
  fi
done
[ -z "$PY" ] && { echo "install: no Python 3 found on PATH. Install Python 3.8+ first." >&2; exit 1; }

mkdir -p "$BIN_DIR"

cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# Auto-generated by the Delegation Pipeline installer. Points at the repo checkout.
exec "$PY" "$REPO_DIR/delegate.py" "\$@"
EOF
chmod +x "$LAUNCHER"
echo "installed launcher -> $LAUNCHER"

if [ ! -f "$CONFIG" ]; then
  cp "$REPO_DIR/config.example.json" "$CONFIG"
  echo "seeded config   -> $CONFIG"
else
  echo "config exists   -> $CONFIG (left unchanged)"
fi

mkdir -p "$CMD_DIR"
cp "$REPO_DIR/commands/delegate.md" "$CMD_DIR/delegate.md"
echo "installed command -> $CMD_DIR/delegate.md  (use /delegate in Claude Code)"

echo
echo "Done. Test it:"
echo "  ~/.claude/bin/delegate free \"list the files here and summarize the project\""
echo
echo "For deepseek/kimi, set your keys (env vars or edit $CONFIG):"
echo "  export DEEPSEEK_API_KEY=sk-..."
echo "  export MOONSHOT_API_KEY=sk-..."
echo "For the free backend, run OmniRoute in another terminal:  npx omniroute"
