#!/usr/bin/env python3
"""Create or refresh the `delegate` launcher in ~/.claude/bin.

Runs as a Claude Code SessionStart hook so that installing the plugin (rather than
cloning the repo) still leaves a working `~/.claude/bin/delegate`. The launcher points
at the plugin's own copy of delegate.py. Stdlib only, Python 3.8+.
"""
import os
import re
import sys

# Matches the generated launcher's `exec "<py>" "<target>" "$@"` line.
_EXEC_RE = re.compile(r'^\s*exec\s+"([^"]*)"\s+"([^"]*)"\s+"\$@"\s*$', re.MULTILINE)


def launcher_target(text):
    """Return the .py path a launcher script execs, or None if it cannot be parsed."""
    m = _EXEC_RE.search(text or "")
    if not m:
        return None
    return m.group(2)


def _launcher_text(python_exe, target):
    posix_target = target.replace("\\", "/")
    return (
        "#!/usr/bin/env bash\n"
        "# Auto-generated by the Delegation Pipeline plugin. Points at the plugin's own copy.\n"
        'exec "%s" "%s" "$@"\n' % (python_exe, posix_target)
    )


def ensure(bin_dir, plugin_root, python_exe=None):
    """Create or refresh the delegate launcher in bin_dir. Returns one of the strings
    "created", "refreshed", or "kept"."""
    target = os.path.join(plugin_root, "delegate.py")
    if not os.path.isfile(target):
        return "kept"

    if python_exe is None:
        python_exe = sys.executable

    launcher = os.path.join(bin_dir, "delegate")

    if os.path.exists(launcher):
        try:
            with open(launcher, "r", encoding="utf-8", errors="replace") as f:
                existing = f.read()
        except OSError:
            existing = ""
        current = launcher_target(existing)
        if current and os.path.exists(current):
            return "kept"
        result = "refreshed"
    else:
        result = "created"

    if not os.path.isdir(bin_dir):
        os.makedirs(bin_dir, exist_ok=True)

    with open(launcher, "w", encoding="utf-8", newline="\n") as f:
        f.write(_launcher_text(python_exe, target))

    if os.name != "nt":
        os.chmod(launcher, 0o755)
    else:
        native = target.replace("/", "\\")
        with open(os.path.join(bin_dir, "delegate.ps1"), "w", encoding="utf-8") as f:
            f.write('& "%s" "%s" $args\n' % (python_exe, native))
        with open(os.path.join(bin_dir, "delegate.cmd"), "w", encoding="utf-8",
                  newline="") as f:
            f.write('@echo off\r\n"%s" "%s" %%*\r\n' % (python_exe, native))

    return result


if __name__ == "__main__":
    try:
        _bin_dir = os.path.join(os.path.expanduser("~"), ".claude", "bin")
        _plugin_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        _result = ensure(_bin_dir, _plugin_root)
        if _result != "kept":
            print("delegate launcher %s -> %s" % (_result, os.path.join(_bin_dir, "delegate")))
    except Exception:
        pass
    sys.exit(0)
